"""Add cascade delete to Lab relationships

Revision ID: b6c21bc597e9
Revises: daba92ba7798
Create Date: 2025-08-17 16:56:51.882260

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b6c21bc597e9"
down_revision: Union[str, None] = "daba92ba7798"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "teacher_profiles_lab_id_fkey", "teacher_profiles", type_="foreignkey"
    )
    op.create_foreign_key(
        "teacher_profiles_lab_id_fkey",
        "teacher_profiles",
        "labs",
        ["lab_id"],
        ["id"],
        ondelete="CASCADE",
    )

    op.drop_constraint(
        "enrollment_cohorts_lab_id_fkey", "enrollment_cohorts", type_="foreignkey"
    )
    op.create_foreign_key(
        "enrollment_cohorts_lab_id_fkey",
        "enrollment_cohorts",
        "labs",
        ["lab_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "enrollment_cohorts_lab_id_fkey", "enrollment_cohorts", type_="foreignkey"
    )
    op.create_foreign_key(
        "enrollment_cohorts_lab_id_fkey",
        "enrollment_cohorts",
        "labs",
        ["lab_id"],
        ["id"],
    )

    op.drop_constraint(
        "teacher_profiles_lab_id_fkey", "teacher_profiles", type_="foreignkey"
    )
    op.create_foreign_key(
        "teacher_profiles_lab_id_fkey", "teacher_profiles", "labs", ["lab_id"], ["id"]
    )
    # ### end Alembic commands ###
